### ISSUE TITLE
А если из 4 или 5 слов?

### ISSUE THREAD

**Issue by coursar** [idris-musin/initial-calculation#2]
https://github.com/idris-musin/initial-calculation/blob/6d374055338f1b8f0ec5e455e8d58f3d00cba10b/src/main/java/ru/itpark/InitialCalculation.java#L7-L13

**Comment by idris-musin** [comment]
Тогда длина массива - 1:

parts[0].substring(0,1) + parts[parts.length - 1].substring(0, 1);
